version: '3.8'

services:

  web:
    build: .
    container_name: diet-django-web
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles


  nginx:
    image: nginx:latest
    container_name: diet-django-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles  #정적 파일 공유 볼륨 추가

volumes:
  static_volume:  #정적 파일 볼륨 정의




