version: '3.8'

services:
  db:
    image: postgres:14
    container_name: diet-django
    restart: always
    environment:
      POSTGRES_DB: diet
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 0000
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: diet-django-web
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: [ "gunicorn", "-b", "0.0.0.0:8000", "main_project_07.wsgi:application" ]


  nginx:
    image: nginx:latest
    container_name: diet-django-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles  #정적 파일 공유 볼륨 추가

volumes:
  pgdata:
  static_volume:  #정적 파일 볼륨 정의





