# Generated by Django 5.1.6 on 2025-02-13 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet', '0001_initial'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portion_size', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_foods', to='diet.diet')),
                ('food', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_diets', to='food.food')),
            ],
            options={
                'unique_together': {('diet', 'food')},
            },
        ),
    ]
