<<<<<<<< HEAD:user/migrations/0002_profile_date.py
# Generated by Django 5.1.6 on 2025-02-14 04:54
========
# Generated by Django 5.1.6 on 2025-02-14 01:41
>>>>>>>> 8ae07ac (profile migrate):user/migrations/0002_profile_image.py

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
