# Generated by Django 5.1.5 on 2025-02-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('contains_nuts', models.BooleanField()),
                ('contains_gluten', models.BooleanField()),
                ('contains_dairy', models.BooleanField()),
            ],
        ),
    ]
