# Generated by Django 5.1.6 on 2025-02-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('contains_nuts', models.BooleanField(default=False)),
                ('contains_gluten', models.BooleanField(default=False)),
                ('contains_dairy', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('labels', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
