#name: Deploy
#
#on:
#  push:
#    branches:
#      - develop
#  pull_request:
#    branches:
#      - develop
#
#jobs:
#  deploy:
#    name: deploy server
#    runs-on: ubuntu-20.04
#
#    steps:
#      - name: repository check
#        uses: actions/checkout@v4
#
#      - name: docker login
#        uses: docker/login-action@v2
#        with:
#          username: ${{secrets.DOCKERHUB_USER}}
#          password: ${{secrets.DOCKERHUB_TOKEN}}
#
#      - name: build and push
#        run: |
